language: java
branches:
  only:
  - master
  - /^\d+\.\d+$/
cache:
  directories:
    - $HOME/.m2
before_cache:
  - rm -rf $HOME/.m2/repository/io/vertx/
jobs:
  include:
    - stage: test
      name: "OpenJDK 8"
      jdk: openjdk8
      script: mvn -Dtest=Http1xTest test
notifications:
  email:
    recipients:
      - secure: "V3kSlUMaHLlFhnbGa567mdKv1/d4iPLHJEWi1llFDeLhu+pJsAGOZOFqr6bN9V0PJIdCGzr9/xqauA2kdunnqICM8iLga0/vvjZWB/G1SXrmPsL820szvU3Id/BLBJzbnZWPNbmMCSyFLgkUuAJ6QLMFGH56RqUst65Z2++VzHU="
    on_success: always
    on_failure: always
